// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pub

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Aino on the Interweb</h1><p>My presence on this global network. Aino is pronounced <i>eye-no</i>.</p><p>I do not like all this fancy web stuff everybody now uses, so this is just plain <a href=\"https://github.com/theaino/aino_site\">HTML written in Go</a>.</p><h3>Contact</h3><p><ul><li>Email: info (at) aino-spring (dot) com (<a href=\"https://keys.openpgp.org/vks/v1/by-fingerprint/7EA40D63698A041361DD3080A2F15C351B9CB710\">PGP key</a>)</li><li>XMPP: aino (at) aino-spring (dot) com</li><li>GitHub: <a href=\"https://github.com/theaino\">&#64;theaino</a></li></ul></p><p>Not going to give you more.</p><h3>Good things</h3><figure><img src=\"/res/imgs/mia.jpg\" alt=\"Sorry that you cannot see my cat.\" style=\"max-width: 100%\" width=\"300\"><figcaption>My cat Mia, shot on Fomapan 200</figcaption></figure><p>Other stuff</p><p><ul><li><a href=\"https://publiccode.eu\">https://publiccode.eu</a></li><li><a href=\"https://motherfuckingwebsite.com\">The excuse I use for this site's \"design\"</a></li><li>I also do some politics (member of <a href=\"https://fdp.de/\">this party</a>)</li></ul></p><h3>Bad things</h3><p>Felix</p><p>Javascript (this site uses 0%)</p><details style=\"cursor: pointer\"><summary>Click to reveal</summary><p>Socialism (check history, it sucks)</p><p>Taxes (they are theft)</p></details>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
