// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pub

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Aino on the Interweb</h1><p>My presence on the global network. Aino is pronounced <i>eye-no</i>.</p><p>I do not like all this fancy web stuff everybody uses (and don't care enough to put that much work into my site), so this is just plain <a href=\"https://github.com/theaino/aino_site\" target=\"_blank\">HTML and Go</a>.</p><h3>Contact</h3><p><ul><li>Email: info (at) aino-spring (dot) com (<a href=\"https://keys.openpgp.org/vks/v1/by-fingerprint/7EA40D63698A041361DD3080A2F15C351B9CB710\">PGP key</a>)</li><li>XMPP: aino (at) aino-spring (dot) com</li><li>Codeberg: <a href=\"https://codeberg.org/theaino\" target=\"_blank\">&#64;theaino</a> (recently tried it out, looks better than github)</li><li>GitHub: <a href=\"https://github.com/theaino\" target=\"_blank\">&#64;theaino</a></li></ul></p><p>I share my current book progress on <a href=\"https://www.goodreads.com/user/show/202602472-aino-spring\" target=\"_blank\">goodreads</a>, for those interested.</p><p>I'm also doing some <a href=\"/gallery\">photography</a>. Don't expect much though.</p><h3>Things I support (and you should too)</h3><p><ul><li><a href=\"https://publiccode.eu\" target=\"_blank\">publiccode.eu</a></li><li><a href=\"https://fightchatcontrol.eu\" target=\"_blank\">fightchatcontrol.eu</a></li><li><a href=\"https://motherfuckingwebsite.com\" target=\"_blank\">The excuse I use for this site's \"design\"</a></li></ul></p><h3>Objectively evil things</h3><ul><li>Javascript (this site uses 0%)</li></ul>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
