services:
  aino_site:
    build: .
    restart: always
    environment:
      SERVER_ADDR: "0.0.0.0:8080"
    ports:
      - "8080:8080"
    networks:
      - aino_network

networks:
  aino_network:
    external: true
    name: aino_network
