# Generated by Django 5.0.6 on 2024-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.CharField(default="Description", max_length=255),
            preserve_default=False,
        ),
    ]
