# Generated by Django 5.1 on 2024-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_category_options_post_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
