# Generated by Django 5.1 on 2024-08-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_post_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_ips',
            field=models.JSONField(default={}, editable=False),
            preserve_default=False,
        ),
    ]
