# Generated by Django 5.1.4 on 2025-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="date",
            field=models.DateField(),
        ),
    ]
